import React, { useState } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Hamburger, Logo } from 'itechartsitewrapper';

export const HomePage = () => {
    const [isPrimary, setIsPrimary] = useState();
    const mouseHandler = () => {
        setIsPrimary(prevState => !prevState)
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Hamburger color="red" />
                <div
                    onMouseEnter={mouseHandler}
                    onMouseLeave={mouseHandler}
                >
                    <Logo mode={isPrimary ? 'primary' : 'secondary'} />
                </div>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>
            </main>
        </div>
    )
}

export default HomePage;